### ISSUE TITLE
Proposta di ospitare lo sviluppo su GitHub Italia

### ISSUE THREAD

**Issue by ruphy** [marcogargano/wppa#1]
Ciao Marco,

sono Riccardo del [Team per la Trasformazione Digitale](https://teamdigitale.governo.it). Non ho potuto fare a meno di non notare l'ottimo lavoro che hai svolto con questo tema wordpress! Mi piacerebbe offrirti la possibilità di ospitare lo sviluppo su [Developers Italia](https://github.com/italia), per renderlo il nostro tema wordpress ufficiale. Ovviamente il copyright, il controllo dei piani di sviluppo e la gestione del repository rimarrebbero con il tuo nome chiaramente indicato, in accordo con le nostre politiche di open governance. Con la migrazione su Developers Italia avresti a disposizione anche gli strumenti (come il [nostro Slack](https://slack.developers.italia.it)) per gestire futuri sviluppi ed interagire con le altre comunità, inclusa quella dei designer (che continua a lavorare e ad aggiornare le linee guida).

Per quanto riguarda il codice, gli unici temi necessari all'onboarding sono la sistemazione del file README per offrire qualche indicazione in più (v. ad esempio il file https://github.com/italia/bootstrap-italia), l'adozione del sistema di metadati [PublicCode](https://github.com/italia/publiccode.yml), e l'apposizione di una [licenza Open Source compatibile](https://teamdigitale.github.io/licenses/README.it.html). Posso aiutarti per tutti questi temi.

Fammi sapere se sei interessato. In ogni caso, gran lavoro! Spero di sentirti presto! :tada:

Ciao,
Riccardo

**Comment by MarcoGargano** [comment]
Ciao @ruphy !
Sono molto contento che ti sia piaciuto il mio lavoro e della proposta che mi hai fatto e... 
accetto molto volentieri! 😁

Per il codice, se mi dai delle indicazioni più precise su cosa inserire nel README le riporto; posso fare un'estrapolazione delle info principali dal link che mi hai suggerito, ma se ci sono informazioni che ritieni importanti da riportare segnalamele pure.
Per quanto riguarda la licenza, le istruzioni mi sembrano molto chiare, invece per l'adozione dei metadati PublicCode preferirei mi aiutassi.
Poi dimmi tu quando passare all'onboarding.

Grazie ancora dell'opportunità di collaborare con la vostra community! 🙏

Aspetto tue,
Marco

**Comment by MarcoGargano** [comment]
Ciao @ruphy 
Ho creato una nuova branch seguendo le tue indicazioni [Branch onboarding](https://github.com/marcogargano/wppa/tree/onboarding/kit/wppa).

Mi rimane da fare il publiccode.yml ... ma ora non riesco.
Ho inserito tutto nella root del tema. 
Spero sia corretto, dimmi tu 😀

**Comment by MarcoGargano** [comment]
Onboarded: https://github.com/italia/design-wordpress-theme 

![olé](http://cultofthepartyparrot.com/parrots/parrot.gif)
